### ISSUE TITLE
Add/enforce maintenance of a Changelog

### ISSUE THREAD

**Issue by tcooper** [hpcng/warewulf#278]
We need a changelog.

Multiple Github actions are available in the marketplace to autogenerate changelog content.

I may prefer one that only requires the `CHANGELOG.md` file be updated along with any PR that is submitted.

Consider... https://github.com/marketplace/actions/changelog-enforcer

**Comment by tcooper** [comment]
[CHANGELOG.md](https://github.com/hpcng/warewulf/blob/main/CHANGELOG.md) was added in [/66efa1d](https://github.com/hpcng/warewulf/commit/66efa1d70d3a985f831cb3d90131b8a28b7cdf84) and has a few updates.

Still consider automation/enforcement for all PRs?

**Comment by mslacken** [comment]
I am unsure about this, on the one side a proper changelog is good, but if it's enforced it's hard to do this for all small changes which just fix e.g. the linting

**Comment by anderbubble** [comment]
I'm looking at

* https://dangoslen.medium.com/enforcing-a-changelog-with-github-actions-279119ed4182
* https://github.com/marketplace/actions/changelog-enforcer

I note particularly

> The Changelog Enforcer is exactly as it sounds — it verifies that a change has been made to a common changelog file on every pull request. You can even skip the enforcement on pull requests that are making changes that don’t worry an update — but it must of course be agreed upon by the author and the reviewer.

I think this sounds quite reasonable. I suggest we enable this and see how we like it, especially since "you can even skip the enforcement on pull requests that are making changes that don’t worry an update."
