### ISSUE TITLE
Messed up warewulf root

### ISSUE THREAD

**Issue by TerranWorks** [hpcng/warewulf#322]
I managed to mess up my warewulf install so now wwctl configure is looking for my /etc/warewulf/warewulf.conf in /usr/local/etc/warewulf/warewulf.conf. How do I set the correct root?

I was going to get on the slack channel instead of making an issue but the invite link on the website seems to be broken. I made an issue over on the warewulf-web repo about it.

**Comment by gmkurtzer** [comment]
Hi @TerranWorks,

It isn't really a messup, just that you probably rebuilt from `main` which changed the build subsystem to put everything in configurable locations with `/usr/local` being the default prefix.

You can either move your config, or rebuild using the following commands to emulate the previous defaults. From memory, I think this will do it:

```
$ make clean
$ make genconfig PREFIX=/var/warewulf SYSCONFDIR=/etc BINDIR=/usr/bin
$ make
$ sudo make install
```

Good luck!

**Comment by TerranWorks** [comment]
I tried your suggestion with PREFIX="" so my config would be in /etc/warewulf and not /var/warewulf/etc/warewulf but it didn't seem to work. I moved my config to /usr/local/etc/warewulf/warewulf.conf but it would be nice to have it just live in /etc/warewulf. Maybe its user error?

**Comment by griznog** [comment]
@TerranWorks here's how I build, forcing everything into different locations:

```
#!/bin/bash

function die () {
  echo $*
  exit 1
}

make \
  PREFIX=/usr \
  LOCALSTATEDIR=/datapool \
  SYSCONFDIR=/etc \
  SRVDIR=/datapool/warewulf/provision \
  clean all build || die "make failed."

make install || die "make install failed."

systemctl daemon-reload
systemctl restart warewulfd
```
If you look in the Makefile most of the variables you can set this way are near the top.

**Comment by TerranWorks** [comment]
Thank you. It still doesn't seem to be working for me even though the output of each command seems to suggest that changes are being made. Something is stuck somewhere and I think it might be the cause of another issue I'm having where warewulf is saying a node is unconfigured even though a configuration exists.

I'm trying to hop on the Warewulf slack channel(the link in the readme requires a username and password and I think its supposed to be an invitation). If I can get on there, I'll bring up this issue. I'm sure I broke something by rebuilding everything so many times and, you know, its arch so... Thanks again

**Comment by griznog** [comment]
It's been a long time since I joined that slack, but as far as I know it doesn't require an invitation. However, to be safe here is a never expiring invite link: https://join.slack.com/t/hpcng/shared_invite/zt-qda4h1ls-OP0Uouq6sSmVE6i_0NrWdw

`SYSCONFDIR` controls where the warewulf config ends up, if you don't explicitly set that then a `/etc/warewulf` will wind up under whatever `PREFIX` is used.

**Comment by griznog** [comment]
I should elaborate on that, you probably don't want `PREFIX=""`, I think that's pretty much expected to be `/usr` for any distro packaged things these days, so `PREFIX=/usr SYSCONFDIR=/etc/` will result in something that is mostly sane (or at least similar to what an `rpm` or `deb` package would do). 

The other two variables I mentioned will be `LOCALSTATEDIR` where chroots and overlays live and `SRVDIR` where all the generated images and kernels will live. I move those because I want them on a different filesystem than `/` so there'd be more room available.

**Comment by TerranWorks** [comment]
Thanks for the permalink. I was able to join the slack channel

**Comment by TerranWorks** [comment]
I found a solution and just wanted to post here in case anyone finds it later. I alternated `` which wwctl `` and deleting that file until I had removed all of them and then performed [gmkurtzer](https://github.com/gmkurtzer)'s steps followed by a `` systemctl daemon-reload `` and `` systemctl restart warewulfd ``. I think when I was trying to rebuild from source (before I knew what I was doing) I must have copied a wwctl file somewhere that wasn't being updated. Thanks for all the help!
