### ISSUE TITLE
docs: manpages for warewulf.conf and nodes.conf

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#510]
We should have manpages for warewulf.conf and nodes.conf that detail all the available settings and their acceptable values.

**Comment by anderbubble** [comment]
I'm happy to work on this; can it be assigned to me?

**Comment by mslacken** [comment]
Thanks for looking into this.

**Comment by anderbubble** [comment]
@mslacken It looks to me like warewulf.conf:dhcp['template'] is no longer used now that DHCP configuration has been moved to the host overlay. Can you confirm?

**Comment by anderbubble** [comment]
warewulf.conf:tftp['tftproot'] also appears to be unused: rather, it appears to be compiled-in, defined in Makefile and warewulf.spec. Can you confirm? Should this be filed as a bug, or removed from the documentation?

**Comment by mslacken** [comment]
> @mslacken It looks to me like warewulf.conf:dhcp['template'] is no longer used now that DHCP configuration has been moved to the host overlay. Can you confirm?
Right. In the 4.3.0 branch the warewulf.conf:dhcp['template'] variable is without effect. 
The question we have right now is, how to handle the host overlays in the future. Due to now solved limits in the templating mechanism, the actual host overlays are just a 1:1 copy from the overlay directory to the host, as it was not possible to address single files for overlay rendering. With that changes we could now go back and have and store this templates for the host under `/etc/` and store distro/site specific changes in `warewulf.conf`. Now this site/distro specifc paths are handled with different rpms.
So whats your take on this?

**Comment by anderbubble** [comment]
I'd probably replace the `warewulf.conf:warewulf:host overlay` with a parameter that takes the name of one or more host overlays to apply, and then use that to specify one or more service-, distro-, and site-specific host configuration overlays. That way host overlays behave even more like compute node overlays.

**Comment by anderbubble** [comment]
Fixed by #511.
