### ISSUE TITLE
Questions about migrating from rocks to warewulf

### ISSUE THREAD

**Issue by edvinas31** [hpcng/warewulf#551]
Hello all,

It is rather discussion, but not an issue of warewulf. We are currently thinking about moving from Rocks cluster 7 to Warewulf and we have couple of questions:

1) Does the warewulf support multiple control node (frontend) NIC's? What we are trying to achieve is to have two groups of compute nodes and each of these groups to be connected to control node. So in ideal scenario we would need control node to have three NIC's: one for public network, another for compute group no1 (connected with private switch) and third one for compute group no3 (connected with another private switch). Every compute node group would use separate switch

2) In Rocks cluster it is great to be able not to specify each compute node ip address manually. Ip address is taken from dhcp when node boots. What about warewulf? Is it really necessary to specify ip addresses before booting the node?

3) In Rocks cluster all the software installed under shared file system which is accessible to all compute nodes. How warewulf actually manages the software in images? Is it usually a new image for specific workload/software or is it using one large image with all software which is needed?

4) What is warewulf compatibility with the nodes which have GPU? Is it common practice? Because in Rocks cluster it is pretty straightforward

Thank you for any answer

**Comment by griznog** [comment]
Hi,

1. Yes, I have had as many as 7 different networks on a single WW master,
with most of those also provisioning nodes on the given network. WW4
assumes it'll just have one network so we have to manually set up the
necessary stuff for them all in DNSMasq, which we use instead of dhcpd.

2. I think the default WW4 network setup stuff in the wwinit overlay
assumes an IP address will be set statically. And if it was using a dynamic
random address from a range, there'd be no way to get the hostname updated
to match the IP. In our environment DNSMasq can handle updating DNS when a
DHCP request comes in and is acknowledged, but even then we still use an
assigned IP address for each node as Slurm really badly wants hostnames to
resolve even when the node is offline so we force them to always exist and
work in the DNSMasq config. So getting the IP dynamically is completely
doable, but it's probably still a good idea to assign an IP to each node
even if the node uses DHCP to set up the interfaces. Doing it
fully dynamically and randomly would require also making the nodes dynamic
in Slurm, perhaps adding them from the provisioning process? Not really
sure how that would all work and at least for us we're not adding/removing
hardware frequently enough to warrant doing that.

3. This is a matter of taste. You could have a minimal node which mounts a
software stack via a network filesystem, usually that is done with modules
(Lmod) and there are tools some people like to manage the stack (Spack,
easybuild,...). You can have everything in one large image as well, with
the caveats that anything over about 2 GB worth of image will need to boot
UEFI instead of Legacy BIOS and some hardware may still have issues with
really large (> 8GB) images.

4. It's possible to install GPU drivers into the image being booted or set
up the images to install the drivers at boot time. We do the latter with a
service which runs at system startup, checks for any recognized GPUs on the
machine and if it finds them, sets up the specified nVidia drivers and
starts the relevant GPU services (persistanced, mostly).

You might want to join the hpcng slack at
https://join.slack.com/t/hpcng/shared_invite/zt-1hkt9dpkw-4Wnr1SkP0~d3VF2MCz7mCw
, specifically the #warewulf channel. It's a good place to get help with
warewulf issues.

Best,

griznog

**Comment by edvinas31** [comment]
Hi @griznog  thank you for such a brief answers. It means a lot to us. I just wanted to be more specific about the setup we try to do (point number 1). I saw warewulf presentation video and this is the exact place what I do expect from the setup https://youtu.be/TgN0QY4zyD0?t=1466 . What I really want to see is some proof of concept of this scheme 
![network_scheme](https://user-images.githubusercontent.com/49708029/194122727-88168ca9-4e89-42e6-ab2a-d2145c540e72.png)

**Comment by edvinas31** [comment]
Our use case is that we have one compute nodes group (connected in switch 1) used for scientific computations and another compute nodes group (connected in switch 2) used for students. What we really want to achieve with that is just to not share same network bandwidth between those to compute node groups as it may affect MPI job results

**Comment by griznog** [comment]
An MPI job running on nodes connected to switch1 should have all (in theory) of it's traffic confined to switch1. Even with both in a single layer 2 network the only interference in traffic will be broadcasts, which for 10 Gbe and greater ethernet is a tiny percentage of available bandwidth. I'd be surprised it it had a noticeable impact on MPI performance and if worried about MPI performance at that level, you'd want to add an Infiniband fabric to provide a lower-latency interconnect for MPI. The analogy there is that if you are spending a lot of time or adding complexity to get the last 1% performance out of your wheelbarrow, it's probably time to think about getting a dump truck instead. 

We're deep into the category of free advice and the value of such at this point, but I'd probably bond a couple of links from the master to switch1, then bond a couple of links from switch1 to switch2 and just let it be a flat layer2 network. Depending on the switches they should either do an excellent job of keeping traffic separate or just a good job of it, but I'd be surprised if bleedover of packets between them caused an issue. 

Something a wise old HPC person once told me that I've found to be very true over the years: "Premature optimization should be avoided." Usually best to get the simple case working, find real bottlenecks then address them.
