### ISSUE TITLE
kmod don't include anything

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#836]
### Version of Warewulf

development branch

### Expected behavior

If a kernel is imported `kmod.img`  should include all the modules and firmare

### Actual behavior

`kmod.img` is empty

### Reason

The `filepath.Match ` in https://github.com/hpcng/warewulf/blob/866348bc932d9c4193d83e6f67b9b9a06bd868a8/internal/pkg/util/util.go#L339 does match the exact pattern, so 
`/lib/firmware/foo` would not be matched by `/lib/firmware`.

**Comment by griznog** [comment]
`kmods.img` really needs to just be removed as a thing WW does in favor of having this all just be in the container. https://github.com/hpcng/warewulf/issues/501 

If we really want a reduced size `initramfs` to boot from, then `dracut` does that much more cleanly and in a distro-and kernel specific way for each container than our attempts to manually build one.

**Comment by mslacken** [comment]
`kmod.img` is only is if another kernel is used. Also #501 seems to be fixed right now.

**Comment by griznog** [comment]
I think #501 is fixed, at least I haven't gotten an error from building a container in a while. But I don't actually use `kmods.img` so I wouldn't notice if it's not there or didn't have the right stuff in it. 

What is the actual use case for `kmods.img` then? My initial understanding was that it would use the master's OS modules to allow a container to not have them installed so that size would be reduced. Is it now being used to boot with kernels that are not present in the container?

**Comment by mslacken** [comment]
The use of this is to exchange the kernel on another container. So if you want to try the SUSE kernel on a rocky container.
